### ISSUE TITLE
There's a back button in the settings view

### ISSUE THREAD

**Issue by zond** [zond/dipact#141]
All other things that we open on top of everything else has a 'dialog window' feeling, where you exit with back button, clicking outside, escape key, or close button.

Since you moved the settings view into the drawer menu, I guess it makes sense that it's not a dialog window (since no other items there open dialog windows), but the others don't have the back button. And it's not obvious that the back button leads back to the 'My Games' item.

What is the goal here, unifority-wise?

**Comment by JorenC** [comment]
That is exactly what I want to stop.

Dialog windows are for alerts, or quick edits (e.g. colour picker dialog
when you change a colour, or "Are you sure?" before you delete something).

We are currently abusing them for many, many things. In the game view, they
work because they're an "extra" part of other content, but we *shouldn't *make
everything a dialog. Now we even get the case that we're opening a dialog
ON TOP OF another dialog (settings > colour picker), which is really NOK.

For side menu items, they are the same hierarchy as the other side-menu
items. Like "My games", "Open games" etc, they open with an app bar. So,
settings should also. The only "inconsistency" is that it changes to a
"back button" rather than a "menu button", but I think that's more then
acceptable, because it also reinforces the "save" state - for any screen
with settings, there is the question of when they are saved - on back
press, on "save/discard", on change? In this case, the back button
reinforces that the elements are saved on change - vs a menu item.

Create new game should ALSO move away from a dialog, and there are some
other instances; for example the player scoreboard...


In addition to the hierarchy issues, dialogs are not the best way to
present information on mobile, because you make the screen smaller than it
is (margin outside of the dialog, and then padding on the inside). This
makes the already limited screen real estate even smaller.


So, I think we're doing fine the way we do now, but I will change some of
these dialogs into fullscreen dialogs with an app bar - basically their own
page implementation...

Unless we need to discuss it more ;)

J

**Comment by zond** [comment]
Sounds great! I just wanted to know what the plan is :D
