### ISSUE TITLE
Release pipeline

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#169]
Now that we are rolling out to 100%, we shouldn't "release to production" as easily.

I suggest: 
- beta-dot-dipact.appspot.com. This is where we work in, where we push updates in. 
- the Beta APK reverts to this domain

- diplicity.com (dipact.appspot.com). This is where we merge the branches once/week. 
- The "normal" APK reverts to this domain.

This ensure we don't mess things up accidentally...

**Comment by zond** [comment]
I agree - the problem is that the app doesn't know if it's a beta or not.

I have reasons to believe it can find out, but that'd take a few network requests, which would delay startup even more.

One idea I have is to assume dipact.appspot.com (or beta-... if it was beta last time, and work with that - in the mean time it would start up as normal, but when the check is done it would - if current != last time - store a new "last time" and then reload the entire app.

Or, what do you suggest?

**Comment by JorenC** [comment]
That could work, automatic solutions would be better.

But I think it would already be okay to have two separate versions of the
APK, like we do now, one hard coded to diplicity.com, one to beta-dot.

I think in general we don't update the wrapper APK so often. It's much more
the loaded website.
This would be more work, but still safe?

**Comment by zond** [comment]
https://stackoverflow.com/questions/24819546/is-it-possible-to-detect-that-an-android-app-is-either-a-beta-version-or-product has an answer that talks about checking the APK list in the Play store, to see if the installed APK is in beta or prod.

**Comment by zond** [comment]
I suggest that we release bug fixes on master, but new features on beta. WDYT?

**Comment by zond** [comment]
After looking more at this, it seems like we'd have to have different app versions in beta and prod, permanently, for that idea to work. That's something that's going to fail pretty easily, when you want to promote a beta to prod.

We need some other way, which is sad because the beta program is so darn convenient.

**Comment by JorenC** [comment]
I don't really see the issue?

99% of the development, functionality and changes are on the website.
The alpha/beta apks are just wrappers.

If we keep the APKs separate by manually needing to change a redirect when
releasing, that is fine, right?

Considering the APK is in 99% of the bugs in feature development not the
root cause, but the underlying website, this wouldn't be a problem?

In the last weeks we made like 100 changes to dipact and 5 to APK...

In my mind, the APK would actually be the same between beta and production
(any change to the apk would be a bug fix and can be uploaded to production
immediately). However, changes in the release of dipact would prevent us
from making mistakes in the code.

This way, you could even have diplicity.com and beta.diplicity.com > it
would be the same thing...

**Comment by zond** [comment]
Very well, I have started work on having two different APK flavors, one for beta and one for prod.

**Comment by zond** [comment]
Alright, now we have a beta app that connects to beta-dot-dipact.appspot.com, and says 'Loading beta app' with a red background when starting up, while the regular app still says 'Loading app' with a black background.
I also made it so that the beta app always has an uneven version number, and one higher than the prod app which has an even number - Play store didn't like prod and beta having the same version numbers...

**Comment by JorenC** [comment]
Very nice! So between you, me and Tom, we now release updates to beta-dot?

**Comment by zond** [comment]
As long as you push to the beta branch yes.

I added something to my startup script to show the branch name in the prompt if within a git project, so as to avoid mistaking which branch I'm on :)
