### ISSUE TITLE
Handle opening a mustering game better

### ISSUE THREAD

**Issue by zond** [zond/dipact#199]
- Don't show the "no orders to submit" toast.
- Show a popup explaining that they must submit to start the game.

**Comment by JorenC** [comment]
Show a "Welcome to the game" dialogue. 
- Don't let users submit. Just say "Yes, I'll join" on the dialogue that submits for the user.
- Have a "I don't want to join"/"cancel" button that lets you leave the game.

**Comment by zond** [comment]
You can't leave the game during mustering... You can just commit, or be a
douche and kill the game :/

**Comment by JorenC** [comment]
Or realise that you've been queing for a week, and now the game actually
starts you won't have time to play, because some work stuff came up. So
rather than start the game and NMR, you back out.

OR, you realise that you have 24 hours but if you confirm right now, it
means the game will start, so you want to wait until after work.

 There should be an escape option. We can just call it "Cancel" and go
back, not able to open the game without pressing "I'm ready".

**Comment by zond** [comment]
Sounds good

**Comment by zond** [comment]
I added a popup explaining what's happening in https://github.com/zond/dipact/commit/ad16cc0fa9b41a6d66dfa2574a846fb07f3b13b7

It'll have to do for now.
