### ISSUE TITLE
Home Screen about "My Games"

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#20]
One major interaction flaw is that when the app opens, your games are not there - you need to look for them in the side menu. 

On the default homescreen (now: notifications), it would be very helpful to combine three lists: "My playing", "My staging" and (possibly) "My finished" - although the latter might be very long.

By having (at least) this interaction here, this means that the player can open the app and immediately enter the game he is playing with one click. 
Additionally, he/she can see if staging games have started (moved to playing) and if playing games have finished (moved to finished). 

![image](https://user-images.githubusercontent.com/7293081/77852420-e1037500-71de-11ea-8246-ad37429cda63.png)

I tried to take a look at doing this, but it's (currently) way beyond my level to combine this. I MIGHT be able to style it, though.
(Also, it would be very nice if we could find out which nation the player is playing so we can load in that flag)

**Comment by zond** [comment]
How about we pick one? If you have started games, just show that list, otherwise if you have staging games, show that list, otherwise show open games?

And then, below this list (which might not show _all_ of the games, but the latest N, or something), we put the "New game"-button.

And what is the "home" of the "New game"-button? Or should it only show up on the start page?

**Comment by JorenC** [comment]
In terms of ease to implement, I think the above is _passable_. However, especially for new users, they will not intuitively look into the side menu, so this means they will not find any staging games if they make one, and need to go on a treasure hunt -which in UX is NOT good-. 

In terms of the ROI, I think it's fine to start with your solution (IF started games, show. ELSE IF staging games, show ELSE IF finished games, show N games ELSE show new game screen).

As for the new game button, Ideally we'd add a slider that I can style into something like this:
https://preview.uxpin.com/e6df2c3c4fd987b7b77fab66ac250f9b5672efdc#/pages/127126035/simulate/no-panels?mode=chidm

Do you think that's doable?

**Comment by zond** [comment]
Sounds good.
Slider, you mean a bottom slider?

**Comment by zond** [comment]
Also - your ideal solution, is that expand panels with the game lists?

**Comment by JorenC** [comment]
No, if you look at the uxpin link, you can press the "new game" button and use a slide https://material-ui.com/zh/api/slide/ component you used earlier to fly in the new game menu > you used this earlier to fly in the chat. 

The idea is that the "new game" menu flies in from the bottom with the new game options. When you click on "join public game" you get forwarded to the "open games" activity (same as side menu > open games), when you get the "find private game" you get the dialog with the ID and if you press "new game" you get the same as the -to be- new game options...

This way, we can use one screen to (easily) have all options available, without a lot of new code...

**Comment by JorenC** [comment]
> Also - your ideal solution, is that expand panels with the game lists?

No, that's not necessary. 
- Join public game > Load new activity with all games
- Find private game > Open current find activity dialog
- Start new game > Do exactly what your future "new game" button would do. 

Ideally though, in the expanded state the "NEW GAME" button would change to "CLOSE" (and when pressing that button or anywhere outside of the fly-in menu, it would close the menu).

**Comment by zond** [comment]
Ah, the uxpin is interactive! Nice! Didn't know that :D

I can build that start menu, and then let you style it - sounds simple enough.

**Comment by zond** [comment]
I submitted https://github.com/zond/dipact/commit/b6f6ed9962d7f3718b7ec65904b8bd2440750153 which sort of solves part of this.

There are some issues:
- There are a lot of extra styling to get the lists to look good when the first element is wrapped in an expansion panel summary. I don't like the brittleness of that.
- To open the game without a View-button, I just wrapped the summary in a div with an onClick. I realise that we might want something like that anyway, but it doesn't hint about the clickability of the summary.. Also, despite my best efforts (e.preventDefault() and e.stopPropagation()) the event bubbles up to the expansion panel which toggles when you open the games?

Otherwise, please comment, beautify, and fix in any way you want :D

**Comment by zond** [comment]
Also, they look like crap on desktop :D

**Comment by zond** [comment]
Alright, I made them slightly less ugly. But the main issues remain.

**Comment by JorenC** [comment]
Awesome! It looks terrible. But we can work on that! The UI is much much better! Saves three clicks every opening

**Comment by zond** [comment]
Sounds good :D
