### ISSUE TITLE
[UX] Back button in chat channel should close chat channel

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#66]
It's how other chat apps work now the app will reload.

**Comment by zond** [comment]
The entire app reloads on back button in all views :/

I tried to create something nicer in one branch, but it's SUPER hard (or a lot of boring and bug prone grunt work)  to make it work everywhere.

Is it enough if it only works in chat? Or would it be confusing if back worked only there?

**Comment by JorenC** [comment]
It doesn't even have to be in the chat. The app works now quite well, it's
just "better". I'll keep pushing for "best".

If it's too hard, just leave it.
If it's not too hard, only on chat, because that's the only back movement
you'll make very often (switching back between different conversations).
There are no real other interactions so far that need a back button
(switching between tabs is not back interaction)

**Comment by zond** [comment]
How about closing game views?

**Comment by JorenC** [comment]
That you don't want to have set to the back button, because if someone accidentally pressed back too often they'd be kicked out of the game. 

IF we would have proper back button routing (I'm all for doing some repetitive menial coding task like this in the future, it helps me understand the basics, but now other priorities) then here you'd want the back button the first time to have a "Press back again to exit" kind of snackbar/toast interaction so you prevent someone pressing back in the chat and accidentally pressing it one time too many

**Comment by zond** [comment]
I mean - when you are viewing a game but not a chat channel, back button will reload the app in the start view. If it just closed the game view in a controlled way it would be quicker to open again, and it's a back action that people would expect, right?

So, back routing that works like "back button does certain well defined things in each view, like close a dialog or a game or a chat channel" is repetitive but not super hard.

Back routing that works like on the web, that it loads whatever was before the current view, is hard - since it has to remember state for all previous views to be able to recreate them, and unless we store all that state in the window location (which is maybe possible, but we don't today because it's so darn convenient to be able to send state between components as complex JS structures - and it feels like building an actual application and not a bunch of weirdly programmed web pages) we have to do that ourselves.

I have a branch that automatically does all of that, but then I ran into the problem that trying to update state to "open and active" for a component that is unmounted is frowned upon by React.

So, we would have to potentially rebuild the entire page view from scratch on every back click.

Which is fine, I guess - maybe slow sometimes? But now we have a much simpler setup where every new dialog and thingie is just a component inside the same page, so opening/closing a game or a chat channel is just showing/creating or hiding/removing a single element.

That means we would have to either rebuild the app from the ground up to not work like that (i.e. it would rebuild everything from scratch every new back-enabled click), or have two different ways of creating the views - one on back clicks and one on regular "forward" clicks.

It all become so messy. Unless there's a better way I vote for disabling back button, or letting it reload like now and teach users not to use it. Both alternatives with exceptions where it makes sense.
