### ISSUE TITLE
[UX] New message refresh on message sent

### ISSUE THREAD

**Issue by JorenC** [zond/dipact#92]
Now, when a new message is sent, it appears as a new message - even if it's my own message and I'm looking at it. 

In a channel, when a message is sent it should count the currently active channel (and the message that is sent) as a read message, while disregarding the other sent messages. 
![image](https://user-images.githubusercontent.com/7293081/80138992-0600c300-85a6-11ea-9400-4c27bdb7bcb6.png)

**Comment by JorenC** [comment]
(In the case above, you can see I sent three messages to Portugal but it is registered as new messages, which feels weird)

**Comment by zond** [comment]
I actually like it, since it shows me which messages are new since I opened the channel. It makes it simple and quick to find those messages. Am I the weird one? :)

**Comment by JorenC** [comment]
It's weird that it happens when you start a negotiation, but I guess we can leave it

**Comment by zond** [comment]
I'm not fanatical about it - if you feel strongly about it let's change it - it's just that I built it like that by chance (since I didn't want the "new messages" thing to disappear the moment we loaded messages, I had to block its updating somehow, and this was the first try) but I liked how it worked :D
